# Pipeline Configuration for O4-Only Training
# This config represents the O4-only approach used for final paper results
# Achieves 97.0% precision, 96.1% recall, ROC-AUC 0.994

# Data directories (compatible with existing pipeline)
downloader:
  data_directories:
    raw_data: ./data/raw
    processed_data: ./data/processed
    manifest_file: ./data/download_manifest.json

  # Data parameters
  sample_rate: 4096  # Hz
  duration: 32       # seconds

  # Science mode validation
  science_min_coverage: 0.80  # Minimum fraction of segment in science mode

  # Download parameters
  download_parameters:
    max_concurrent: 4
    timeout_seconds: 60
    retry_attempts: 3
    retry_delay: 1.0

  # Signal download settings - O4 ONLY
  signals:
    events: []
    detectors: [H1]
    runs: [O4a, O4b]  # O4 only for single-run training

  # Noise download settings
  noise:
    runs: [O1, O2, O3a, O3b, O4a]  # All observing runs for diverse noise training
    detectors: [H1]
    segments_per_run: 500
    min_gap: 64

# Preprocessing configuration
preprocessing:
  cwt:
    target_height: 8
    target_width: 4096
    use_analytic: true
    fmin: 20
    fmax: 512

# Model configuration
model:
  architecture: "cwt_lstm"
  latent_dim: 32
  input_height: 8
  input_width: 4096
  
  anomaly_detection:
    scoring_strategy: 'mean'

# Training configuration
training:
  epochs: 20
  batch_size: 1
  learning_rate: 0.001
  optimizer: "sgd"
  loss_function: "mse"
  early_stopping_patience: 5
  min_improvement: 0.001
  model_dir: 'models'

# Evaluation configuration
evaluation:
  threshold_method: "optimal"
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "roc_auc"
    - "pr_auc"

# Pipeline metadata
pipeline:
  run_name: 'o4_only_final'
  description: 'O4-only training (GWTC-4.0) eliminating cross-run batch effects'
  version: '2.2.0'
  observing_run: 'O4'
  catalog: 'GWTC-4.0'
  
  data_flow:
    preprocessed_data_dir: 'data/processed'

# IMPORTANT NOTE:
# This run achieved 97.0% precision, 96.1% recall, ROC-AUC 0.994
# Training: 1592 noise segments (all runs)
# Testing: 102 O4 signals + 399 noise segments
# O4 signals: 126 total in GWTC-4.0, 102 successfully processed for evaluation
