downloader:
  data_directories:
    raw_data: "data/raw/"
    processed_data: "data/processed/"
    manifest_file: "data/download_manifest.json"
  
  detectors:
    - "H1"
    - "L1"
  
  observing_runs:
    - "O1"
    - "O2"
    - "O3a"
  
  # Test with just a few noise segments - using valid science-mode GPS times
  noise_segments:
    - start_gps: 1126101488
      end_gps: 1126101520
      label: "test_noise_H1_001"
      type: "noise"
      detector: "H1"
      duration: 32
      sample_rate: 4096
    - start_gps: 1126101488
      end_gps: 1126101520
      label: "test_noise_L1_001"
      type: "noise"
      detector: "L1"
      duration: 32
      sample_rate: 4096
    - start_gps: 1126101600
      end_gps: 1126101632
      label: "test_noise_H1_002"
      type: "noise"
      detector: "H1"
      duration: 32
      sample_rate: 4096
    - start_gps: 1126101600
      end_gps: 1126101632
      label: "test_noise_L1_002"
      type: "noise"
      detector: "L1"
      duration: 32
      sample_rate: 4096
  
  # Test with one signal segment
  signal_segments:
    - start_gps: 1126259450
      end_gps: 1126259482
      label: "GW150914_H1"
      type: "signal"
      detector: "H1"
      duration: 32
      sample_rate: 4096
      known_event: "GW150914"
    - start_gps: 1126259450
      end_gps: 1126259482
      label: "GW150914_L1"
      type: "signal"
      detector: "L1"
      duration: 32
      sample_rate: 4096
      known_event: "GW150914"
  
  download_parameters:
    max_concurrent: 2
    timeout_seconds: 60
    retry_attempts: 3
    retry_delay: 5
  
  data_quality:
    validate_downloads: true
    check_file_integrity: true
    max_nan_percentage: 50.0
    max_inf_percentage: 50.0
