name: Check Dependencies
on: [push, pull_request]

jobs:
  deps:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pipdeptree
      
      - name: Check for outdated packages
        run: |
          pipdeptree --warn fail
          echo "Dependencies check completed successfully"
