name: Code Quality
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
      
      - name: Run flake8
        run: flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203,W503,E501
      
      - name: Check black formatting
        run: black --check src/ tests/
      
      - name: Check import sorting
        run: isort --check-only src/ tests/
